-- S&P 500 시가총액 상위 100개 종목 시드
-- 시가총액 순위는 시점에 따라 변동. 이 시드는 2025~2026 기준의 일반적인 상위 종목.
-- 일부 ticker 표기는 데이터 소스마다 다를 수 있음 (예: BRK.B vs BRK-B).
-- 가격 수집(Finnhub/Yahoo)에서 fail하는 ticker는 V5+에서 보정.

INSERT INTO stocks (ticker, name, market) VALUES
    ('AAPL', 'Apple Inc.', 'NASDAQ'),
    ('MSFT', 'Microsoft Corporation', 'NASDAQ'),
    ('GOOGL', 'Alphabet Inc. Class A', 'NASDAQ'),
    ('GOOG', 'Alphabet Inc. Class C', 'NASDAQ'),
    ('AMZN', 'Amazon.com Inc.', 'NASDAQ'),
    ('NVDA', 'NVIDIA Corporation', 'NASDAQ'),
    ('META', 'Meta Platforms Inc.', 'NASDAQ'),
    ('TSLA', 'Tesla Inc.', 'NASDAQ'),
    ('BRK.B', 'Berkshire Hathaway Inc. Class B', 'NYSE'),
    ('UNH', 'UnitedHealth Group Inc.', 'NYSE'),
    ('JPM', 'JPMorgan Chase & Co.', 'NYSE'),
    ('JNJ', 'Johnson & Johnson', 'NYSE'),
    ('V', 'Visa Inc.', 'NYSE'),
    ('PG', 'Procter & Gamble Co.', 'NYSE'),
    ('XOM', 'Exxon Mobil Corporation', 'NYSE'),
    ('MA', 'Mastercard Inc.', 'NYSE'),
    ('HD', 'Home Depot Inc.', 'NYSE'),
    ('AVGO', 'Broadcom Inc.', 'NASDAQ'),
    ('LLY', 'Eli Lilly and Company', 'NYSE'),
    ('CVX', 'Chevron Corporation', 'NYSE'),
    ('ABBV', 'AbbVie Inc.', 'NYSE'),
    ('KO', 'Coca-Cola Company', 'NYSE'),
    ('PEP', 'PepsiCo Inc.', 'NASDAQ'),
    ('MRK', 'Merck & Co. Inc.', 'NYSE'),
    ('COST', 'Costco Wholesale Corporation', 'NASDAQ'),
    ('WMT', 'Walmart Inc.', 'NYSE'),
    ('TMO', 'Thermo Fisher Scientific Inc.', 'NYSE'),
    ('ADBE', 'Adobe Inc.', 'NASDAQ'),
    ('BAC', 'Bank of America Corporation', 'NYSE'),
    ('CSCO', 'Cisco Systems Inc.', 'NASDAQ'),
    ('PFE', 'Pfizer Inc.', 'NYSE'),
    ('NFLX', 'Netflix Inc.', 'NASDAQ'),
    ('ORCL', 'Oracle Corporation', 'NYSE'),
    ('CRM', 'Salesforce Inc.', 'NYSE'),
    ('ABT', 'Abbott Laboratories', 'NYSE'),
    ('AMD', 'Advanced Micro Devices Inc.', 'NASDAQ'),
    ('ACN', 'Accenture plc', 'NYSE'),
    ('INTC', 'Intel Corporation', 'NASDAQ'),
    ('NKE', 'Nike Inc.', 'NYSE'),
    ('DIS', 'Walt Disney Company', 'NYSE'),
    ('WFC', 'Wells Fargo & Company', 'NYSE'),
    ('MCD', 'McDonald''s Corporation', 'NYSE'),
    ('TXN', 'Texas Instruments Inc.', 'NASDAQ'),
    ('UNP', 'Union Pacific Corporation', 'NYSE'),
    ('PM', 'Philip Morris International Inc.', 'NYSE'),
    ('NEE', 'NextEra Energy Inc.', 'NYSE'),
    ('RTX', 'RTX Corporation', 'NYSE'),
    ('UPS', 'United Parcel Service Inc.', 'NYSE'),
    ('LIN', 'Linde plc', 'NYSE'),
    ('CMCSA', 'Comcast Corporation', 'NASDAQ'),
    ('T', 'AT&T Inc.', 'NYSE'),
    ('INTU', 'Intuit Inc.', 'NASDAQ'),
    ('HON', 'Honeywell International Inc.', 'NASDAQ'),
    ('QCOM', 'Qualcomm Inc.', 'NASDAQ'),
    ('LOW', 'Lowe''s Companies Inc.', 'NYSE'),
    ('AMGN', 'Amgen Inc.', 'NASDAQ'),
    ('SBUX', 'Starbucks Corporation', 'NASDAQ'),
    ('IBM', 'International Business Machines Corp.', 'NYSE'),
    ('SPGI', 'S&P Global Inc.', 'NYSE'),
    ('CAT', 'Caterpillar Inc.', 'NYSE'),
    ('GS', 'Goldman Sachs Group Inc.', 'NYSE'),
    ('AXP', 'American Express Company', 'NYSE'),
    ('MDT', 'Medtronic plc', 'NYSE'),
    ('ELV', 'Elevance Health Inc.', 'NYSE'),
    ('BLK', 'BlackRock Inc.', 'NYSE'),
    ('ISRG', 'Intuitive Surgical Inc.', 'NASDAQ'),
    ('NOW', 'ServiceNow Inc.', 'NYSE'),
    ('BKNG', 'Booking Holdings Inc.', 'NASDAQ'),
    ('DE', 'Deere & Company', 'NYSE'),
    ('SYK', 'Stryker Corporation', 'NYSE'),
    ('MMC', 'Marsh & McLennan Companies Inc.', 'NYSE'),
    ('ADP', 'Automatic Data Processing Inc.', 'NASDAQ'),
    ('SCHW', 'Charles Schwab Corporation', 'NYSE'),
    ('PLD', 'Prologis Inc.', 'NYSE'),
    ('C', 'Citigroup Inc.', 'NYSE'),
    ('CB', 'Chubb Limited', 'NYSE'),
    ('AMAT', 'Applied Materials Inc.', 'NASDAQ'),
    ('ADI', 'Analog Devices Inc.', 'NASDAQ'),
    ('GILD', 'Gilead Sciences Inc.', 'NASDAQ'),
    ('TGT', 'Target Corporation', 'NYSE'),
    ('MO', 'Altria Group Inc.', 'NYSE'),
    ('ZTS', 'Zoetis Inc.', 'NYSE'),
    ('VRTX', 'Vertex Pharmaceuticals Inc.', 'NASDAQ'),
    ('LRCX', 'Lam Research Corporation', 'NASDAQ'),
    ('REGN', 'Regeneron Pharmaceuticals Inc.', 'NASDAQ'),
    ('PYPL', 'PayPal Holdings Inc.', 'NASDAQ'),
    ('EQIX', 'Equinix Inc.', 'NASDAQ'),
    ('CI', 'Cigna Group', 'NYSE'),
    ('PGR', 'Progressive Corporation', 'NYSE'),
    ('TJX', 'TJX Companies Inc.', 'NYSE'),
    ('BSX', 'Boston Scientific Corporation', 'NYSE'),
    ('MU', 'Micron Technology Inc.', 'NASDAQ'),
    ('SO', 'Southern Company', 'NYSE'),
    ('CME', 'CME Group Inc.', 'NASDAQ'),
    ('ETN', 'Eaton Corporation plc', 'NYSE'),
    ('SLB', 'Schlumberger N.V.', 'NYSE'),
    ('MDLZ', 'Mondelez International Inc.', 'NASDAQ'),
    ('KLAC', 'KLA Corporation', 'NASDAQ'),
    ('PANW', 'Palo Alto Networks Inc.', 'NASDAQ'),
    ('APD', 'Air Products and Chemicals Inc.', 'NYSE'),
    ('FI', 'Fiserv Inc.', 'NYSE'),
    ('USB', 'U.S. Bancorp', 'NYSE'),
    ('DUK', 'Duke Energy Corporation', 'NYSE')
ON CONFLICT (ticker) DO NOTHING;
